on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please-main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          RELEASE_PLEASE_PAT: op://Development/RELEASE_PLEASE_PAT/token
      
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ env.RELEASE_PLEASE_PAT }}
          target-branch: main
          config-file: .github/release-please/release-please-config.json
          manifest-file: .github/release-please/.release-please-manifest.json
      